import type {CMS,PageDocument,Section,Product,AdminData} from './schema';
export const blankStyles=()=>({desktop:{},tablet:{},mobile:{}});
export const makeSection=(type:Section['type'],title='새 섹션'):Section=>({id:crypto.randomUUID(),type,eyebrow:'',title,body:'내용을 입력하세요.',image:'',backgroundImage:'',buttonText:'상담받기',buttonHref:'/consulting',secondaryButtonText:'',secondaryButtonHref:'',visible:true,animation:'none',styles:blankStyles(),elements:[]});
const names=['JETINNO','JETINNO','JETINNO','JETINNO','CIME','CIME'];
export const products:Product[]=Array.from({length:6},(_,i)=>({id:`machine-${i+1}`,name:`Coffee Machine 0${i+1}`,brand:names[i],model:'',image:`/machines/machine-0${i+1}.webp`,gallery:[],video:'',category:i<4?'전자동':'반자동',description:'공간에 어울리는 머신을 만나보세요. 실제 모델과 공급 가능 여부를 확인한 후, 사용 환경에 맞는 제품을 안내해 드립니다.',features:['사용 환경에 맞춘 제품 상담','설치 조건 확인 후 견적 안내','제품 및 공급 가능 여부 상담'],specs:'',size:'',weight:'',power:'',water:'확인 필요',environment:i<4?'사무실, 가정':'카페, 음식점',usage:'확인 필요',price:null,priceMode:'상담 후 견적',featured:true,isNew:false,published:true,stock:'공급 여부 상담',seoTitle:'',seoDescription:''}));
const policyText='운영자가 실제 사업 조건과 개인정보 처리 과정을 확인한 후 입력할 정책 템플릿입니다. 현재는 확정된 약관이 아닙니다. 운영 개시 전 실제 사업자 정보, 처리 목적, 보유 기간, 배송·교환·환불 조건과 문의 창구를 검토해 주세요.';
export const seedCMS:CMS={settings:{name:'FORME',tagline:'COFFEE & MACHINES',logo:'',favicon:'',phone:'',email:'',business:'',businessNumber:'',owner:'',address:'',commerce:'',sns:'',kakao:'',footer:'좋은 원두의 마지막 완성.\n당신의 공간에 맞는 커피머신을 제안합니다.',copyright:'© FORME COFFEE. All rights reserved.',disclaimer:'본 사이트는 독립적으로 운영되는 판매·상담 채널이며 에이덴 공식 홈페이지가 아닙니다.',seoTitle:'FORME COFFEE | 원두의 가치를 살리다.',seoDescription:'공간과 목적에 맞는 프리미엄 커피머신. 제품 소개부터 전문 상담, 견적까지.',floating:{visible:true,position:'right',color:'#22221f',text:'고객상담',inquiryText:'문의하기',size:44,icon:'message',href:'/consulting',inquiryHref:'/contact'},policies:{terms:policyText,privacy:policyText,shipping:policyText,returns:policyText,refund:policyText}},products,brands:['JETINNO','CIME'],categories:['전자동','반자동','업소용','사무실용','기타'],navigation:[['home','HOME','/'],['products','PRODUCTS','/products'],['brands','BRANDS','/brands'],['consulting','CONSULTING','/consulting'],['about','ABOUT','/about'],['journal','JOURNAL','/journal'],['contact','CONTACT','/contact']].map(([id,name,href])=>({id,name,href,visible:true,children:id==='products'?[{id:'all',name:'전체 머신',href:'/products',visible:true},...['전자동','반자동','업소용','사무실용','기타'].map((name,i)=>({id:`cat${i}`,name,href:`/products?category=${encodeURIComponent(name)}`,visible:true}))]:[]})),showcase:{auto:true,speed:4,direction:'left',size:290,perspective:1100,spacing:15,pause:2,items:products.map(p=>({id:p.id,image:p.image,name:p.name,productId:p.id,active:true}))},media:products.map(p=>({id:p.id,name:p.name,url:p.image,createdAt:'2026-10-04T00:00:00Z'}))};
const section=(id:string,type:Section['type'],title:string,body:string,eyebrow='',buttonText='',buttonHref='/consulting'):Section=>({...makeSection(type,title),id,body,eyebrow,buttonText,buttonHref});
export const seedPages:Record<string,PageDocument>={home:{title:'원두의 가치를 살리다.',description:seedCMS.settings.seoDescription,sections:[section('hero','hero','원두의 가치를\n살리다.','좋은 원두의 마지막 완성은 머신에서 결정됩니다.\n공간과 목적에 맞는 커피머신을 제안합니다.','THE ART OF A GOOD CUP','커피머신 보기','/products'),section('collection','products','좋은 커피를 위한,\n당신의 머신.','작은 일상의 한 잔부터 공간의 시그니처까지.\n당신에게 맞는 한 대를 찾는 여정.','THE COLLECTION'),section('philosophy','cta','기준은 커피.\n시작은 당신의 공간.','어떤 머신이 필요한지 모르시겠나요?\n사용량, 설치 환경, 예산을 함께 살펴봅니다.','CURATED FOR YOUR SPACE','나에게 맞는 머신 상담받기') ]},products:{title:'The Collection',description:'프리미엄 커피머신 컬렉션',sections:[section('product-intro','text','당신의 공간에,\n가장 좋은 한 대.','제품을 고르는 일은 좋은 커피를 만드는 첫걸음입니다.','THE COLLECTION')]},about:{title:'About FORME',description:'독립 커피머신 전문 판매·상담 채널',sections:[section('about-intro','text','한 잔의 가치를,\n공간의 가치로.','좋은 머신은 좋은 원두가 가진 가능성을 꺼냅니다.\n우리는 당신의 취향과 공간을 이해하는 데서 시작합니다.','OUR POINT OF VIEW'),{...section('about-image','image','',''),image:'/machines/machine-05.webp'},section('about-process','grid','고르고, 상담하고, 완성하다.','제품 확인 → 사용 환경 상담 → 추천과 견적 → 주문 확정 → 공급처 발주 → 배송·설치 안내','HOW WE WORK'),section('about-cta','cta','좋은 선택을, 함께.','본 사이트는 독립 판매·상담 채널입니다. 실제 판매자 관계와 서비스 조건은 운영자가 확인 후 안내합니다.','LET’S TALK','상담 시작하기')]},contact:{title:'Contact',description:'제품 문의와 상담',sections:[section('contact-intro','text','좋은 커피의 시작,\n이야기해 주세요.','제품에 대한 작은 궁금증부터 새로운 공간을 위한 제안까지.','GET IN TOUCH')]}};
export function initialData():AdminData{return {cms:structuredClone(seedCMS),revision:0,pages:Object.fromEntries(Object.entries(seedPages).map(([k,v])=>[k,{draft:structuredClone(v),published:structuredClone(v),revision:0}])),inquiries:[],logs:[],orders:[],versions:[],mode:'local'};}
