import 'server-only';
import {cookies} from 'next/headers';
import {createServerClient} from '@supabase/ssr';
import {createClient} from '@supabase/supabase-js';
import {createHmac,timingSafeEqual,randomUUID} from 'node:crypto';
import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import path from 'node:path';
import type {AdminData,CMS,PageRecord,PageDocument} from './schema';
import {initialData,seedCMS,seedPages} from './seed';
import {publicCMS} from './domain';
export const configured=()=>!!(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
export const localEnabled=()=>process.env.NODE_ENV!=='production'&&process.env.LOCAL_SANDBOX==='true'&&(process.env.LOCAL_ADMIN_PASSWORD?.length??0)>=12&&(process.env.LOCAL_SESSION_SECRET?.length??0)>=32;
export const mode=()=>localEnabled()?'local':configured()?'supabase':'unconfigured';
export async function supabase(){if(!configured())throw new Error('Supabase 연결이 필요합니다.');const jar=await cookies();return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{cookies:{getAll:()=>jar.getAll(),setAll:values=>{try{values.forEach(({name,value,options})=>jar.set(name,value,options));}catch{/* 서버 컴포넌트 읽기에서 쿠키 갱신은 route handler 담당 */}}}});}
export function service(){if(!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('문의 저장용 서버 키 설정이 필요합니다.');return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});}
export function signSession(expires:number){const payload=String(expires);return `${payload}.${createHmac('sha256',process.env.LOCAL_SESSION_SECRET!).update(payload).digest('hex')}`;}
export function verifyLocalSession(token:string|undefined){if(!localEnabled()||!token)return false;const [expiry,signature]=token.split('.');if(!signature||Number(expiry)<Date.now()||Number(expiry)>Date.now()+24*60*60*1000)return false;const expected=signSession(Number(expiry)).split('.')[1];return signature.length===expected.length&&timingSafeEqual(Buffer.from(signature),Buffer.from(expected));}
export async function adminAllowed(){if(localEnabled())return verifyLocalSession((await cookies()).get('forme_admin')?.value);if(!configured())return false;const client=await supabase();const {data:{user},error}=await client.auth.getUser();if(error||!user)return false;const {data}=await client.from('profiles').select('is_admin').eq('id',user.id).single();return data?.is_admin===true;}
export async function requireAdmin(){if(!await adminAllowed())throw new Error('관리자 로그인이 필요합니다.');}
const dataFile=()=>path.join(process.cwd(),'.local-data','store.json');
let queue:Promise<unknown>=Promise.resolve();
export async function readLocal():Promise<AdminData>{try{return JSON.parse(await readFile(dataFile(),'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;return initialData();}}
export function mutateLocal<T>(fn:(state:AdminData)=>T|Promise<T>):Promise<T>{const run=queue.then(async()=>{const state=await readLocal();const result=await fn(state);await mkdir(path.dirname(dataFile()),{recursive:true});const temporary=dataFile()+'.'+randomUUID()+'.tmp';await writeFile(temporary,JSON.stringify(state),'utf8');await rename(temporary,dataFile());return result;});queue=run.catch(()=>{});return run;}
export function sanitizePublic(cms:CMS):CMS{const visible=new Set(cms.products.filter(p=>p.published).map(p=>p.id));return {...cms,products:cms.products.filter(p=>p.published),showcase:{...cms.showcase,items:cms.showcase.items.filter(i=>i.active&&visible.has(i.productId))}};}
export async function getPublic(){if(localEnabled()){const state=await readLocal();return {cms:sanitizePublic(publicCMS(state)),pages:Object.fromEntries(Object.entries(state.pages).map(([k,v])=>[k,v.published])) as Record<string,PageDocument>,mode:mode()};}if(configured()){const client=await supabase();const [c,p]=await Promise.all([client.rpc('get_public_cms'),client.rpc('get_public_pages')]);if(c.error||p.error)throw new Error('공개 콘텐츠를 불러오지 못했습니다. Supabase migration을 확인하세요.');return {cms:sanitizePublic(c.data??seedCMS),pages:{...seedPages,...p.data} as Record<string,PageDocument>,mode:mode()};}return {cms:seedCMS,pages:seedPages,mode:mode()};}
export async function getAdmin():Promise<AdminData>{await requireAdmin();if(localEnabled())return readLocal();const client=await supabase();const results=await Promise.all([client.from('cms_state').select('*').eq('id','main').maybeSingle(),client.from('pages').select('*'),client.from('inquiries').select('*').order('created_at',{ascending:false}),client.from('consultation_logs').select('*').order('created_at',{ascending:false}),client.from('orders').select('*').order('created_at',{ascending:false}),client.from('section_versions').select('*').order('created_at',{ascending:false}).limit(100)]);for(const r of results)if(r.error)throw new Error('관리 데이터를 읽지 못했습니다. DB Schema와 권한을 확인하세요.');const base=initialData();const pages=Object.fromEntries((results[1].data??[]).map(p=>[p.slug,{draft:p.draft,published:p.published,revision:p.revision}])) as Record<string,PageRecord>;return {cms:results[0].data?.document??seedCMS,revision:results[0].data?.revision??0,pages:{...base.pages,...pages},inquiries:results[2].data??[],logs:results[3].data??[],orders:results[4].data??[],versions:results[5].data??[],mode:'supabase'};}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(!origin)return false;try{const parsed=new URL(origin);const configuredOrigin=process.env.NEXT_PUBLIC_SITE_URL?new URL(process.env.NEXT_PUBLIC_SITE_URL).origin:null;return parsed.origin===new URL(request.url).origin||parsed.origin===configuredOrigin||((parsed.protocol==='https:'||process.env.NODE_ENV!=='production')&&parsed.host===request.headers.get('host'));}catch{return false;}}
export function jsonError(error:unknown,status=400){const message=error instanceof Error?error.message:'처리하지 못했습니다.';return Response.json({error:message},{status:message.includes('관리자 로그인')?401:status});}
const limits=new Map<string,{count:number;until:number}>();
export function localRate(key:string,maximum=5,window=600000){const now=Date.now();if(limits.size>10000)for(const [k,v] of limits)if(v.until<now)limits.delete(k);const value=limits.get(key);if(!value||value.until<now){limits.set(key,{count:1,until:now+window});return true;}value.count++;return value.count<=maximum;}

