'use client';
import type {CMS} from '@/lib/schema';
import Image from 'next/image';
export function Field({label,value,onChange,area=false,type='text',placeholder=''}:{label:string;value:string|number;onChange:(value:string)=>void;area?:boolean;type?:string;placeholder?:string}){return <label className="admin-field">{label}{area?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
const optionLabels:Record<string,string>={hero:'메인 3D Hero',text:'텍스트',image:'이미지',products:'제품 컬렉션',cta:'상담 CTA',grid:'그리드',spacer:'여백',none:'없음',fade:'부드러운 등장',left:'왼쪽',center:'가운데',right:'오른쪽',contain:'전체 이미지 보이기',cover:'영역 채우기',auto:'자동',message:'말풍선',phone:'전화',home:'HOME',about:'ABOUT',contact:'CONTACT'};
export function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label className="admin-field">{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o} value={o}>{o?(optionLabels[o]||o):'기본 / 선택 안 함'}</option>)}</select></label>}
export function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="admin-toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/></label>}
export function ImagePicker({label,value,onChange,cms}:{label:string;value:string;onChange:(value:string)=>void;cms:CMS}){return <div className="admin-image-picker"><label className="admin-field">{label}<select value={value} onChange={e=>onChange(e.target.value)}><option value="">이미지 없음</option>{cms.media.map(m=><option key={m.id} value={m.url}>{m.name}</option>)}</select></label>{value&&<div className="picker-preview"><Image src={value} alt={label} fill sizes="220px"/></div>}</div>}
export function Slider({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number;step?:number}){return <label className="admin-slider"><span>{label}<b>{value}</b></span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
