'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight} from 'lucide-react';
import type {BlockStyle,CMS,PageDocument,Section,Element} from '@/lib/schema';
import {Showcase} from './showcase';
export function styleVariables(styles:{desktop:BlockStyle;tablet:BlockStyle;mobile:BlockStyle}){const css:Record<string,string>={};const map:Record<string,string>={fontSize:'font-size',fontWeight:'font-weight',color:'color',align:'align',lineHeight:'line-height',letterSpacing:'letter-spacing',padding:'padding',margin:'margin',background:'background',columns:'columns',gap:'gap',width:'width',height:'height',radius:'radius',border:'border',fit:'fit',ratio:'ratio',hidden:'display'};for(const [breakpoint,values] of Object.entries(styles)){for(const [key,value] of Object.entries(values)){if(value===undefined)continue;let v=String(value);if(['fontSize','letterSpacing','padding','margin','gap','height','radius','border'].includes(key))v+='px';if(key==='width')v+='%';if(key==='hidden')v=value?'none':'block';css[`--${breakpoint}-${map[key]}`]=v;}const ratio=values.ratio;css[`--${breakpoint}-image-height`]=values.height!==undefined?`${values.height}px`:ratio&&ratio!=='auto'?'auto':'250px';}return css as React.CSSProperties;}
function EditableElement({element}:{element:Element}){const e=element;const style=styleVariables(e.styles);if(e.type==='image')return e.src?<div className="builder-element editable-image responsive-block" style={style}><Image src={e.src} alt={e.alt||e.text} fill sizes="(max-width: 768px) 90vw, 50vw"/></div>:<div className="builder-placeholder">이미지를 선택해 주세요.</div>;if(e.type==='button')return <Link className="builder-element button responsive-block" style={style} href={e.href||'/consulting'}>{e.text}<ArrowUpRight size={16}/></Link>;return <p className="builder-element responsive-block" style={style}>{e.text}</p>;}
export function ProductCards({cms,limit}:{cms:CMS;limit?:number}){const published=cms.products.filter(p=>p.published);const featured=published.filter(p=>p.featured);return <div className="product-grid">{(featured.length?featured:published).slice(0,limit).map((p,i)=><article className="product-card" key={p.id}><Link href={`/products/${p.id}`} className="product-photo"><span className="product-number">{String(i+1).padStart(2,'0')}</span><Image src={p.image} alt={`${p.brand} ${p.name}`} fill sizes="(max-width: 650px) 90vw, (max-width: 1000px) 45vw, 30vw"/><span className="product-category">{p.category}</span><span className="photo-arrow"><ArrowUpRight size={21}/></span></Link><div className="product-caption"><span className="eyebrow">{p.brand}</span><h3><Link href={`/products/${p.id}`}>{p.name}</Link></h3><p>{p.priceMode==='가격 표시'&&p.price!==null?`₩ ${p.price.toLocaleString()}`:p.priceMode}</p></div></article>)}</div>}
function ActionLink({className,href,text,size=17}:{className:string;href:string;text:string;size?:number}){return text?<Link className={className} href={href||'/consulting'}>{text}<ArrowUpRight size={size}/></Link>:null;}
export function SectionBlock({section:s,cms,primary=false}:{section:Section;cms:CMS;primary?:boolean}){const Heading=primary?'h1':'h2';if(!s.visible)return null;const style={...styleVariables(s.styles),...(s.backgroundImage?{backgroundImage:`url("${s.backgroundImage}")`,backgroundSize:'cover'}:{})};let content;if(s.type==='hero')content=<div className="hero-content"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span/> {s.eyebrow}</div><h1>{s.title}</h1><p>{s.body}</p><div className="hero-actions"><ActionLink className="button dark" href={s.buttonHref} text={s.buttonText}/><ActionLink className="text-link" href={s.secondaryButtonHref??'/consulting'} text={s.secondaryButtonText??'고객상담'} size={17}/></div><div className="hero-footnote"><span>01 — 06</span>CURATED MACHINES. CONSIDERED CHOICES.</div></div><Showcase cms={cms}/></div>;else if(s.type==='products')content=<div className="section-container"><div className="section-heading"><div><span className="eyebrow">{s.eyebrow}</span><Heading>{s.title}</Heading></div><div><p>{s.body}</p><ActionLink className="text-link" href={s.buttonHref} text={s.buttonText} size={18}/></div></div><ProductCards cms={cms} limit={3}/></div>;else if(s.type==='cta')content=<div className="cta-content"><div><span className="eyebrow">{s.eyebrow}</span><Heading>{s.title}</Heading><p>{s.body}</p><ActionLink className="button light" href={s.buttonHref} text={s.buttonText} size={18}/></div><div className="cta-art"><span>f.</span><div className="cta-art-line"/><small>COFFEE. SPACE. YOU.</small></div></div>;else if(s.type==='image')content=s.image?<div className="section-image"><Image src={s.image} alt={s.title||'커피머신 소개 이미지'} fill sizes="90vw"/></div>:<div className="builder-placeholder">이미지를 선택해 주세요.</div>;else if(s.type==='spacer')content=<div className="spacer-size"/>;else content=<div className="section-container editorial-text"><span className="eyebrow">{s.eyebrow}</span><Heading>{s.title}</Heading><p>{s.body}</p>{s.type==='grid'&&<div className="process-grid">{['사용 환경 상담','추천과 견적','배송·설치 안내'].map((name,i)=><div key={name}><small>0{i+1}</small><h3>{name}</h3><ArrowRight size={20}/></div>)}</div>}<ActionLink className="button dark" href={s.buttonHref} text={s.buttonText} size={16}/></div>;return <section className={`page-section section-${s.type} responsive-block ${s.animation==='fade'?'animate-section':''}`} style={style}>{content}{s.elements.length>0&&<div className="section-elements">{s.elements.map(e=><EditableElement key={e.id} element={e}/>)}</div>}</section>}
export function PageRenderer({document,cms,onSelect,selected}:{document:PageDocument;cms:CMS;onSelect?:(id:string)=>void;selected?:string}){return <div className="page-renderer">{document.sections.map((section,index)=><div key={section.id} className={onSelect?`selectable-section ${selected===section.id?'selected':''}`:''} onClick={onSelect?e=>{e.preventDefault();onSelect(section.id);}:undefined}>{onSelect&&<span className="selection-label">{section.type.toUpperCase()} · {section.title.slice(0,24)||'여백'}</span>}<SectionBlock section={section} cms={cms} primary={index===0}/></div>)}</div>}

