'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,Check,Copy,X} from 'lucide-react';
import type {Product} from '@/lib/schema';
import {compareHref,MAX_COMPARE_PRODUCTS,parseCompareIds} from '@/lib/comparison';
export {compareHref,MAX_COMPARE_PRODUCTS,parseCompareIds};
const storageKey='showroom-compare-products';
export function DetailCompareButton({product,products}:{product:Product;products:Product[]}){const router=useRouter();const [full,setFull]=useState(false);function add(){let ids:string[]=[];try{ids=parseCompareIds(localStorage.getItem(storageKey)||'',products);}catch{}if(!ids.includes(product.id)&&ids.length>=MAX_COMPARE_PRODUCTS){setFull(true);return;}const next=[...new Set([...ids,product.id])];try{localStorage.setItem(storageKey,next.join(','));}catch{}router.push(compareHref(next));}return <div><button type="button" className="text-link" onClick={add}>비교에 담기 <ArrowUpRight size={17}/></button>{full&&<p role="status">이미 3개를 선택했습니다. <Link href="/compare">비교 목록에서 제품 변경하기</Link></p>}</div>;}
export function useCompareSelection(initialIds:string[],products:Product[],path='/products'){const router=useRouter();const initialKey=initialIds.join(',');const productKey=products.map(p=>p.id).join(',');const [ids,setIds]=useState(()=>parseCompareIds(initialKey,products));useEffect(()=>{const initial=parseCompareIds(initialKey,products);let next=initial;try{if(initial.length)localStorage.setItem(storageKey,initial.join(','));else next=parseCompareIds(localStorage.getItem(storageKey)||'',products);}catch{}const timer=window.setTimeout(()=>setIds(next),0);return()=>window.clearTimeout(timer);},[initialKey,productKey,products]);const update=(next:string[])=>{const valid=parseCompareIds(next.join(','),products);setIds(valid);try{localStorage.setItem(storageKey,valid.join(','));}catch{}router.replace(compareHref(valid,path),{scroll:false});};return [ids,update] as const;}
export function CompareToggle({product,selectedIds,onChange}:{product:Product;selectedIds:string[];onChange:(ids:string[])=>void}){const selected=selectedIds.includes(product.id);return <button type="button" className={`compare-toggle ${selected?'selected':''}`} disabled={!selected&&selectedIds.length>=MAX_COMPARE_PRODUCTS} aria-pressed={selected} onClick={()=>selected?onChange(selectedIds.filter(id=>id!==product.id)):onChange([...selectedIds,product.id])}>{selected?<><Check size={14}/> 비교 선택됨</>:'비교에 담기'}</button>;}
export function CompareSelection({selectedIds,onChange}:{selectedIds:string[];onChange:(ids:string[])=>void}){const router=useRouter();if(!selectedIds.length)return null;return <aside className="compare-selection" aria-live="polite"><div><span className="eyebrow">PRODUCT COMPARISON</span><strong>{selectedIds.length}개 제품 선택</strong><small>최대 {MAX_COMPARE_PRODUCTS}개까지 비교할 수 있습니다.</small></div><div className="compare-selection-actions"><button type="button" onClick={()=>onChange([])}>선택 해제</button><button type="button" className="button dark" disabled={selectedIds.length<2} onClick={()=>router.push(compareHref(selectedIds))}>비교하기 <ArrowUpRight size={16}/></button></div></aside>;}
const confirm=(value:string|number|null|undefined)=>value===null||value===undefined||value===''?'상담 시 확인':String(value);
const fields:{label:string;value:(p:Product)=>string;detail?:boolean}[]=[{label:'모델',value:p=>confirm(p.model)},{label:'크기',value:p=>confirm(p.size)},{label:'무게',value:p=>confirm(p.weight)},{label:'전원',value:p=>confirm(p.power)},{label:'급수 방식',value:p=>confirm(p.water)},{label:'하루 권장 추출량',value:p=>confirm(p.usage)},{label:'권장 사용 환경',value:p=>confirm(p.environment)},{label:'주요 특징',value:p=>p.features.length?p.features.join('\n'):'상담 시 확인',detail:true},{label:'상세 사양',value:p=>confirm(p.specs),detail:true},{label:'가격 안내',value:p=>p.priceMode==='가격 표시'&&p.price!==null?`₩ ${p.price.toLocaleString()}`:confirm(p.priceMode)}];
export function ProductComparison({products,initialIds}:{products:Product[];initialIds:string[]}){const [ids,setIds]=useCompareSelection(initialIds,products,'/compare');const [differencesOnly,setDifferencesOnly]=useState(false);const [copied,setCopied]=useState(false);const selected=useMemo(()=>ids.map(id=>products.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p)),[ids,products]);const rows=fields.filter(field=>!differencesOnly||new Set(selected.map(field.value)).size>1);const copy=async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}${compareHref(ids)}`);setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{}};return <div className="section-container comparison-page"><div className="page-intro comparison-intro"><span className="eyebrow">PRODUCT COMPARISON</span><h1>한 화면에서,<br/>더 선명하게 비교하세요.</h1><p>선택한 제품의 확인된 정보를 나란히 살펴볼 수 있습니다.</p></div>{selected.length<2?<section className="comparison-empty"><h2>{selected.length===1?'비교할 제품을 하나 더 선택해 주세요.':'비교할 제품을 선택해 주세요.'}</h2><p>카탈로그에서 최대 {MAX_COMPARE_PRODUCTS}개까지 담아 크기, 사용 환경, 하루 권장 추출량과 주요 사양을 비교할 수 있습니다.</p><Link className="button dark" href={compareHref(ids,'/products')}>제품 보러가기 <ArrowUpRight size={16}/></Link></section>:<><div className="comparison-controls"><label><input type="checkbox" checked={differencesOnly} onChange={e=>setDifferencesOnly(e.target.checked)}/> 차이 있는 항목만 보기</label><button type="button" onClick={copy}><Copy size={15}/>{copied?'링크를 복사했습니다':'비교 링크 복사'}</button></div><p className="comparison-note">하루 권장 추출량은 음료 구성과 운영 조건에 따라 달라질 수 있으며, 최대 처리량을 뜻하지 않습니다.</p><div className="comparison-scroll"><table className="comparison-table"><thead><tr><th scope="col">비교 항목</th>{selected.map(p=><th scope="col" key={p.id}><button type="button" className="comparison-remove" onClick={()=>setIds(ids.filter(id=>id!==p.id))} aria-label={`${p.name} 비교에서 제거`}><X size={16}/></button><div className="comparison-product-image">{p.image?<Image src={p.image} alt="" fill sizes="180px"/>:<span>이미지 준비 중</span>}</div><span>{p.brand}</span><strong>{p.name}</strong><Link href={`/products/${p.id}`}>상세 보기 <ArrowUpRight size={13}/></Link></th>)}</tr></thead><tbody>{rows.map(field=><tr key={field.label}><th scope="row">{field.label}</th>{selected.map(p=><td className={field.detail?'comparison-detail':''} key={p.id}>{field.value(p)}</td>)}</tr>)}{differencesOnly&&!rows.length&&<tr><td className="comparison-same" colSpan={selected.length+1}>입력된 비교 정보가 동일합니다. 전체 항목 보기를 선택해 확인해 주세요.</td></tr>}</tbody><tfoot><tr><th scope="row">상담</th>{selected.map(p=><td key={p.id}><Link className="button dark" href={`/consulting?product=${p.id}`}>제품 상담 <ArrowUpRight size={14}/></Link></td>)}</tr></tfoot></table></div><div className="comparison-bottom-actions"><Link className="text-link" href={compareHref(ids,'/products')}>제품 더 담기 <ArrowUpRight size={16}/></Link><button type="button" onClick={()=>setIds([])}>전체 선택 해제</button></div></>}</div>;}
