'use client';
import Link from 'next/link';
import Image from 'next/image';
import {useState} from 'react';
import {ArrowUpRight,Menu,X,MessageCircle,Phone} from 'lucide-react';
import type {CMS} from '@/lib/schema';
export function Header({cms}:{cms:CMS}){const [open,setOpen]=useState(false);return <><div className="topline"><span>INDEPENDENT COFFEE MACHINE CURATION</span><span>좋은 커피를 위한, 좋은 선택.</span></div><header className="site-header"><Link href="/" className="wordmark" aria-label={`${cms.settings.name} 홈`}>{cms.settings.logo?<Image src={cms.settings.logo} width={150} height={40} alt={cms.settings.name}/>:<><strong>{cms.settings.name}</strong><small>{cms.settings.tagline}</small></>}</Link><nav className={open?'public-nav is-open':'public-nav'} aria-label="주 메뉴">{cms.navigation.filter(n=>n.visible).map(n=><div className="nav-item" key={n.id}><Link href={n.href} onClick={()=>setOpen(false)}>{n.name}</Link>{n.children.some(c=>c.visible)&&<div className="nav-sub">{n.children.filter(c=>c.visible).map(c=><Link key={c.id} href={c.href} onClick={()=>setOpen(false)}>{c.name}</Link>)}</div>}</div>)}</nav><Link href="/consulting" className="header-cta">고객상담 <ArrowUpRight size={15}/></Link><button className="mobile-menu" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></>}
export function Footer({cms}:{cms:CMS}){const s=cms.settings;return <footer className="site-footer"><div className="footer-top"><div><div className="footer-wordmark">{s.name}</div><p>{s.footer}</p></div><div><span className="eyebrow">A BETTER CUP STARTS HERE</span><Link href="/consulting" className="footer-consult">당신의 다음 한 잔을 위해 <ArrowUpRight/></Link><div className="footer-links"><Link href="/products">커피머신</Link><Link href="/contact">문의하기</Link><Link href="/about">브랜드 이야기</Link>{s.sns&&<a href={s.sns} target="_blank" rel="noreferrer">SNS ↗</a>}</div></div></div><div className="footer-legal"><p>{s.disclaimer}</p>{(s.business||s.phone)&&<p>{[s.business,s.owner&&`대표 ${s.owner}`,s.businessNumber&&`사업자번호 ${s.businessNumber}`,s.commerce&&`통신판매 ${s.commerce}`,s.address,s.phone,s.email].filter(Boolean).join(' | ')}</p>}<div className="legal-links"><span>{s.copyright}</span><div><Link href="/policies/terms">이용약관</Link><Link href="/policies/privacy">개인정보처리방침</Link><Link href="/policies/shipping">배송</Link><Link href="/policies/returns">교환·반품</Link><Link href="/policies/refund">환불</Link><Link href="/business">사업자 정보</Link></div></div></div></footer>}
export function FloatingCTA({cms}:{cms:CMS}){const s=cms.settings.floating;if(!s.visible)return null;const Icon=s.icon==='phone'?Phone:MessageCircle;return <aside className={`floating-cta ${s.position}`} style={{'--float-color':s.color,'--float-size':s.size+'px'} as React.CSSProperties} aria-label="빠른 상담"><Link href={s.href||'/consulting'}><Icon size={16}/>{s.text}</Link><Link href={s.inquiryHref||'/contact'}>{s.inquiryText}<ArrowUpRight size={15}/></Link></aside>}

