'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play} from 'lucide-react';
import {useReducedMotion} from 'motion/react';
import type {CMS} from '@/lib/schema';
export function Showcase({cms}:{cms:CMS}){const items=cms.showcase.items.filter(i=>i.active&&cms.products.some(p=>p.id===i.productId&&p.published));const config=cms.showcase;const ring=useRef<HTMLDivElement>(null);const angle=useRef(0);const hovered=useRef(false);const dragging=useRef(false);const previous=useRef(0);const resumeAt=useRef(0);const [front,setFront]=useState(0);const [paused,setPaused]=useState(false);const reduced=useReducedMotion();const n=items.length;const width=config.size;const radius=n>=3?width/(2*Math.tan(Math.PI/n))+config.spacing:180;
useEffect(()=>{if(!n)return;let frame=0,last=0;function tick(now:number){const dt=last?Math.min(now-last,40)/1000:0;last=now;if(config.auto&&!paused&&!reduced&&!hovered.current&&!dragging.current&&!document.hidden&&now>resumeAt.current)angle.current+=dt*config.speed*(config.direction==='left'?-1:1);if(ring.current)ring.current.style.transform=`rotateX(-5deg) rotateY(${angle.current}deg)`;const index=((Math.round(-angle.current/(360/n))%n)+n)%n;setFront(current=>current===index?current:index);frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[n,config.auto,config.speed,config.direction,paused,reduced]);
function step(direction:number){angle.current-=direction*360/n;resumeAt.current=performance.now()+config.pause*1000;}
const item=items[front];const product=cms.products.find(p=>p.id===item?.productId);return <div className="showcase" role="region" aria-label="3D 커피머신 전시"><div className="showcase-top"><span className="eyebrow">THE ROTATING SHOWROOM</span><span className="showcase-index">{String(front+1).padStart(2,'0')} / {String(n).padStart(2,'0')}</span></div><div className="showcase-scene" style={{perspective:config.perspective+'px','--panel-width':width+'px','--ring-radius':radius+'px'} as React.CSSProperties} tabIndex={0} aria-label="좌우 방향키 또는 드래그로 머신 회전" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1);}if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}}} onPointerEnter={()=>hovered.current=true} onPointerLeave={()=>hovered.current=false} onPointerDown={e=>{if(e.button!==0)return;dragging.current=true;previous.current=e.clientX;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!dragging.current)return;angle.current+=(e.clientX-previous.current)*.33;previous.current=e.clientX;}} onPointerUp={()=>{dragging.current=false;resumeAt.current=performance.now()+config.pause*1000;}} onPointerCancel={()=>dragging.current=false}><div className="showcase-floor"/><div className="showcase-ring" ref={ring}>{items.map((i,index)=><div key={i.id} className={`machine-face ${front===index?'is-front':''}`} style={{transform:`rotateY(${index*360/n}deg) translateZ(${radius}px)`}}><span className="face-number">FORME SELECT / 0{index+1}</span><Image src={i.image} alt={i.name} fill sizes="(max-width: 700px) 220px, 320px" priority={index<3} draggable={false}/><span className="face-caption">{cms.products.find(p=>p.id===i.productId)?.brand} — COFFEE MACHINE</span></div>)}</div>{!n&&<p>전시할 머신을 관리자에서 추가해 주세요.</p>}</div><div className="showcase-bottom"><div className="machine-info" aria-live="polite"><span className="eyebrow">{product?.brand||'COFFEE MACHINE'}</span><Link href={product?`/products/${product.id}`:'/products'}>{item?.name||'머신 컬렉션'} <ArrowUpRight size={19}/></Link><p>{product?'당신의 공간에 어울리는 한 대를 만나보세요.':'제품 컬렉션을 확인해 주세요.'}</p></div><div className="showcase-controls"><button aria-label="이전 머신" onClick={()=>step(-1)}><ChevronLeft size={17}/></button><button aria-label={paused?'자동 회전 재생':'자동 회전 정지'} onClick={()=>setPaused(!paused)}>{paused?<Play size={13}/>:<Pause size={13}/>}</button><button aria-label="다음 머신" onClick={()=>step(1)}><ChevronRight size={17}/></button></div></div><div className="drag-note">DRAG TO EXPLORE <span>↔</span></div></div>}
